version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
      - run:
          name: found github actions config
          command: ':'
  test-e2e:
    docker:
      - image: mcr.microsoft.com/playwright:bionic
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Run Playwright Tests
          command: npx playwright test --reporter=html
      - store_artifacts:
          path: playwright-report
          destination: e2e-test-report
workflows:
  build_and_test:
    jobs:
      - build-node
      - test-e2e:
          requires:
            - build-node
    # - deploy:
    #     requires:
    #       - build-node